Flags = -Wall -Wreturn-type -pedantic -pedantic-errors -Wundef -std=c++11 -O2
CPP = g++

A : Makefile  A.cpp
	$(CPP) $(Flags) -o A A.cpp

B : Makefile  B.cpp
	$(CPP) $(Flags) -o B B.cpp

C : Makefile  C.cpp
	$(CPP) $(Flags) -o C C.cpp

D : Makefile  D.cpp
	$(CPP) $(Flags) -o D D.cpp

E : Makefile  E.cpp
	$(CPP) $(Flags) -o E E.cpp